global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'school-back'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend:8080']   # utilise le nom du service Docker

